"""Updated Artist Schema

Revision ID: 27dcac7d4ab8
Revises: afd08b9df8ba
Create Date: 2022-08-13 14:35:57.035151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27dcac7d4ab8'
down_revision = 'afd08b9df8ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('looking_for_venue', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'looking_for_venue')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
