"""Updated Venue Schema

Revision ID: afd08b9df8ba
Revises: 9fc9fa7639a5
Create Date: 2022-08-13 14:20:33.525013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd08b9df8ba'
down_revision = '9fc9fa7639a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('is_seeking_talents', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talents_description', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_talents_description')
    op.drop_column('Venue', 'is_seeking_talents')
    # ### end Alembic commands ###
