"""Modified fields: Venue + Artist

Revision ID: f21c65cd8072
Revises: 4a489ca90567
Create Date: 2022-08-13 15:26:52.645958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21c65cd8072'
down_revision = '4a489ca90567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.String(length=120), nullable=True))
    op.drop_column('Artist', 'looking_for_venue')
    op.add_column('Venue', sa.Column('seeking_talents', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.drop_column('Venue', 'seeking_talents_description')
    op.drop_column('Venue', 'is_seeking_talents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('is_seeking_talents', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('seeking_talents_description', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'seeking_talents')
    op.add_column('Artist', sa.Column('looking_for_venue', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
